import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Cakes by Naty',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
      <link rel="preload" href="/fondos/fondo.webp" as="image" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
