name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # CI
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build services with Docker Compose
        run: docker-compose -f docker-compose.yml build

      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Run backend tests inside Docker
        run: docker-compose exec server npm run test

      - name: Run frontend tests inside Docker
        working-directory: ./frontend
        run: docker-compose exec app npm run test

      - name: Shut down Docker Compose
        run: docker-compose -f docker-compose.yml down

  # CD
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker Compose
        run: |
         docker-compose -f docker-compose.yml down
         docker-compose -f docker-compose.yml up -d